# Generated by Django 5.0.1 on 2024-01-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_smile_smile_avg_goal_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='smile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='home.smile'),
        ),
    ]
