# Generated by Django 5.0.1 on 2024-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
