# Generated by Django 5.0.1 on 2024-01-29 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_userjoinedcommunity_name_community_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='max_users',
        ),
        migrations.AddField(
            model_name='community',
            name='current_users',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userjoinedcommunity',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.community'),
        ),
    ]
