# Generated by Django 5.0.1 on 2024-01-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_community_options_remove_community_max_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoinedcommunity',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.community'),
        ),
    ]
