# Generated by Django 5.0.1 on 2024-01-24 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('age', models.CharField(choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('64+', '64 and older')], max_length=10)),
                ('relationship_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=15)),
                ('Children', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_step3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('option1', 'I want to increase happiness'), ('option2', 'I want to express gratitude'), ('option3', 'I want an energy boost'), ('option4', 'I want to feel more confident'), ('option5', 'I want to feel more relaxed'), ('option6', 'I want to feel peace'), ('option7', 'I want to reduce stress'), ('option8', 'I want to calm anxiety'), ('option9', 'I want to lower my blood pressure and heart rate')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
