# Generated by Django 5.0.1 on 2024-01-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_children_profile_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='children',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married')], max_length=15, null=True),
        ),
    ]
